# Generated by Django 5.2.7 on 2025-10-28 18:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=32, unique=True)),
                ("year", models.PositiveIntegerField()),
                (
                    "case_type",
                    models.CharField(
                        choices=[
                            ("CIVIL", "Civil"),
                            ("CRIMINAL", "Criminal"),
                            ("WRIT", "Writ"),
                            ("TAX", "Tax"),
                            ("OTHER", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SUMMARY", "Summary"),
                            ("REGULAR", "Regular"),
                            ("COMPLEX", "Complex"),
                        ],
                        default="REGULAR",
                        max_length=16,
                    ),
                ),
                ("complexity", models.PositiveSmallIntegerField(default=2)),
                ("urgency_level", models.PositiveSmallIntegerField(default=1)),
                ("public_interest", models.BooleanField(default=False)),
                ("statutory_deadline", models.DateField(blank=True, null=True)),
                ("priority_score", models.IntegerField(default=0)),
                ("priority_explain", models.JSONField(blank=True, default=list)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("FILED", "Filed"),
                            ("ADMITTED", "Admitted"),
                            ("LISTED", "Listed"),
                            ("HEARD", "Heard"),
                            ("ORDER_RESERVED", "Order Reserved"),
                            ("DISPOSED", "Disposed"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("filing_date", models.DateField(default=django.utils.timezone.now)),
                ("admitted_date", models.DateField(blank=True, null=True)),
                ("next_hearing_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-priority_score", "filing_date"],
            },
        ),
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("PETITIONER", "Petitioner"),
                            ("RESPONDENT", "Respondent"),
                            ("INTERVENOR", "Intervenor"),
                        ],
                        max_length=16,
                    ),
                ),
                ("advocate", models.CharField(blank=True, max_length=128)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parties",
                        to="cases.case",
                    ),
                ),
            ],
        ),
    ]
