# Generated by Django 5.2.7 on 2025-10-28 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Judge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("specializations", models.JSONField(blank=True, default=list)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="TimeStandard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_type", models.CharField(max_length=16)),
                ("category", models.CharField(max_length=16)),
                ("first_listing_days", models.PositiveIntegerField(default=30)),
                ("disposal_days", models.PositiveIntegerField(default=365)),
            ],
        ),
        migrations.CreateModel(
            name="Bench",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("courtroom", models.CharField(blank=True, max_length=32)),
                ("capacity_per_day", models.PositiveIntegerField(default=30)),
                ("specialization_tags", models.JSONField(blank=True, default=list)),
                (
                    "judges",
                    models.ManyToManyField(
                        related_name="benches", to="scheduling.judge"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScheduleSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("capacity_units", models.PositiveIntegerField(default=1)),
                (
                    "allocated_case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cases.case",
                    ),
                ),
                (
                    "bench",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="scheduling.bench",
                    ),
                ),
            ],
            options={
                "unique_together": {("bench", "date", "start_time", "end_time")},
            },
        ),
    ]
